export const translations: Record<string, Partial<typeof text>> = {
	'be-BY': {
		OPEN_SETTINGS: 'Адкрыць дадатковыя налады',
		SUBTITLES: 'Субтытры',
		SPEED: 'Хуткасьць',
		CUSTOM_SPEED: 'Свая Хуткасьць',
		CUSTOM_SPEED_HINT:
			'Калі вызначана, будзе выкарыстоўвацца замест "Хуткасьць"',
		QUALITY: 'Якасьць',
		VOLUME: 'Гучнасьць, %',
		GLOBAL: 'Глябальна',
		LOCAL: 'Гэты Канал',
		SHORTS: 'Адкрываць shorts як звычайныя',
		NEW_TAB: 'Адкрываць відэа ў новай картцы',
		COPY_SUBS: 'Капіяваць субтытры ў поўнаэкранным, Ctrl+C',
		STANDARD_MUSIC_SPEED: 'Звычайная хуткасьць на каналах музыкаў',
		ENHANCED_BITRATE: 'Палепшаны бітрэйт (для карыстальнікаў Premium)',
		SAVE: 'Захаваць',
		EXPORT: 'Экспарт',
		IMPORT: 'Імпарт',
	},
};
export const text = {
	OPEN_SETTINGS: 'Open additional settings',
	SUBTITLES: 'Subtitles',
	SPEED: 'Speed',
	CUSTOM_SPEED: 'Custom Speed',
	CUSTOM_SPEED_HINT: 'If defined, will be used instead of "Speed"',
	QUALITY: 'Quality',
	VOLUME: 'Volume, %',
	GLOBAL: 'Global',
	LOCAL: 'This Channel',
	SHORTS: 'Open shorts as regular videos',
	NEW_TAB: 'Open videos in new tab',
	COPY_SUBS: 'Copy subtitles by Ctrl+C in fullscreen mode',
	STANDARD_MUSIC_SPEED: 'Normal speed on artist channels',
	ENHANCED_BITRATE: 'Quality: Enhanced bitrate (for Premium users)',
	SAVE: 'Save',
	DEFAULT: '-',
	EXPORT: 'Export',
	IMPORT: 'Import',
};
