name: Release
on:
  push:
    branches:
      - 'main'

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          version: 7
      - uses: oven-sh/setup-bun@v1
      - run: bun i --frozen-lockfile
      - run: bun run build
      - run: echo "SCRIPT_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          tag: v${{ env.SCRIPT_VERSION }}
